# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Devdeploy
    variables:
    -  name: Dev
    jobs:
    - job: devdeploymentjob
      steps:
      - bash: echo Devdeploy job is run now 
    - job: devdeploymentjob2
      steps:
      - bash: echo building $(name)_environment 
      - bash: echo devdeploy job 2 is run now
      - bash: echo $(PipelineLevelVariable)

  - stage: QAdeploy
    variables:
      environment: QA
    dependsOn: Devdeploy
    jobs:
    - job: qadeploymentjob
      steps:
      - bash: echo building $(environment)_environment
      - bash: echo building $(name)_environment
      - bash: echo qadeploy job is run now 
    - job: qadeploymentjob2
      steps:
      - bash: echo qadeploy job 2 is run now
      - bash: echo $(PipelineLevelVariable)

  - stage: Proddeploy
    dependsOn:
    - Devdeploy
    - QAdeploy
    jobs:
    - job: proddeployjob
      steps:
      - bash: echo prod deploy job
      - bash: $(PipelineLevelVariable)
